### ISSUE TITLE
How to use nuScenes V1.0-mini for training and evaluation

### ISSUE THREAD

**Issue by wwdlh** [haomo-ai/Cam4DOcc#4]
The amount of data in v1.0-trainval is too large

**Comment by BIT-MJY** [comment]
hi @wwdlh ,

Thanks for your interest in our work. We have not used V1.0-mini for training and evaluation since its data is not enough for reasonable convergence. However, you can evaluate our released model on it by replacing the data-related paths as the bbox-wise gt is generated automatically. Welcome to post your results here!

**Comment by YANG-Deep** [comment]
hi @wwdlh Did you succeed with the mini dataset? Can you tell me how to operate it
