### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by zkyyyyyyy** [haomo-ai/Cam4DOcc#8]
Hi，
I am trying to run training code in this repository with 5 GPUs, but as training continues, more and more training time is required. Can you help me with it?

<img width="1569" alt="87697c6fafa8904dbd40ca7abc17d861" src="https://github.com/haomo-ai/Cam4DOcc/assets/168450210/8838bd5c-8b18-4e1f-a8f3-24622f97e0d3">

**Comment by BIT-MJY** [comment]
Hello @zkyyyyyyy ,

Thanks for using our code. We generate datasets within the first epoch. Please ignore the estimated training time.

**Comment by zkyyyyyyy** [comment]
> Hello @zkyyyyyyy ,
> 
> Thanks for using our code. We generate datasets within the first epoch. Please ignore the estimated training time now and it will be referable in later epochs.

Hi !
After the first epoch, the estimate training time for 24 epochs is still about two weeks, about 4 seconds for one sample. 
Is this training time normal？
<img width="1411" alt="676fa8aeca49c9c8c1ce56328023e35f" src="https://github.com/haomo-ai/Cam4DOcc/assets/168450210/a104f3b6-3de3-4010-a227-02ffaff8d064">

**Comment by BIT-MJY** [comment]
Yes. If you use all the training samples, the training process lasts around one week using our hardware setups. Alternatively, you can uniformly decrease the training samples since there are many pair-wise sequences with large overlap (e.g., 0-1-2-3-4 and 1-2-3-4-5) for faster training. Besides, there are several code implementations that will be optimized for acceleration in our future version.
